// src/data/examples/componentComposition/props/angular/child.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "app-child",
  template: `
    <div>
      <h1>{{ title }}</h1>
      <p>Count: {{ count }}</p>
      <p>Status: {{ isActive ? "Active" : "Inactive" }}</p>
    </div>
  `,
})
export class ChildComponent {
  @Input() title!: string;
  @Input() count: number = 0;
  @Input() isActive: boolean = false;
}

// src/data/examples/componentComposition/props/solid/ChildComponent.tsx
interface ChildProps {
  title: string;
  count?: number;
  isActive?: boolean;
}

function ChildComponent(props: ChildProps) {
  const count = () => props.count ?? 0;
  const isActive = () => props.isActive ?? false;

  return (
    <div>
      <h1>{props.title}</h1>
      <p>Count: {count()}</p>
      <p>Status: {isActive() ? "Active" : "Inactive"}</p>
    </div>
  );
}

export default ChildComponent;
