// src/data/examples/componentComposition/props/react/ChildComponent.tsx
interface ChildProps {
  title: string;
  count?: number;
  isActive?: boolean;
}

function ChildComponent({ title, count = 0, isActive = false }: ChildProps) {
  return (
    <div>
      <h1>{title}</h1>
      <p>Count: {count}</p>
      <p>Status: {isActive ? "Active" : "Inactive"}</p>
    </div>
  );
}

export default ChildComponent;

// src/data/examples/componentComposition/props/angular-renaissance/child.component.ts
import { Component, input } from "@angular/core";

@Component({
  selector: "app-child",
  template: `
    <div>
      <h1>{{ title() }}</h1>
      <p>Count: {{ count() }}</p>
      <p>Status: {{ isActive() ? "Active" : "Inactive" }}</p>
    </div>
  `,
})
export class ChildComponent {
  title = input.required<string>();
  count = input(0);
  isActive = input(false);
}
