// src/data/examples/componentComposition/props/vue3/Parent.vue
<template>
  <div>
    <ChildComponent :title="pageTitle" :count="counter" :is-active="isActive" />
  </div>
</template>

<script setup>
import { ref } from "vue";
import ChildComponent from "./ChildComponent.vue";

const pageTitle = ref("Hello World");
const counter = ref(42);
const isActive = ref(true);
</script>

// src/data/examples/componentComposition/props/angular-renaissance/parent.component.ts
import { Component, signal } from "@angular/core";

@Component({
  selector: "app-parent",
  template: `
    <div>
      <app-child
        [title]="pageTitle()"
        [count]="counter()"
        [isActive]="isActive()"
      >
      </app-child>
    </div>
  `,
})
export class ParentComponent {
  pageTitle = signal("Hello World");
  counter = signal(42);
  isActive = signal(true);
}
