// src/data/examples/componentComposition/slot/angular/parent.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-parent",
  template: `
    <div>
      <app-card>
        <h2>Card Title</h2>
        <p>This is the card content</p>
        <button>Action Button</button>
      </app-card>
    </div>
  `,
})
export class ParentComponent {}

// src/data/examples/componentComposition/slot/vue2/Parent.vue
<template>
  <div>
    <CardComponent>
      <h2>Card Title</h2>
      <p>This is the card content</p>
      <button>Action Button</button>
    </CardComponent>
  </div>
</template>

<script>
import CardComponent from "./CardComponent.vue";

export default {
  components: { CardComponent },
};
</script>
