// src/data/examples/componentComposition/emitToParent/vue3/Parent.vue
<template>
  <div>
    <p>Count: {{ count }}</p>
    <ChildComponent @increment="handleIncrement" @decrement="handleDecrement" />
  </div>
</template>

<script setup>
import { ref } from 'vue'
import ChildComponent from './ChildComponent.vue'

const count = ref(0)

const handleIncrement = () => {
  count.value++
}

const handleDecrement = () => {
  count.value--
}
</script>

// src/data/examples/componentComposition/emitToParent/angular-renaissance/parent.component.ts
import { Component, signal } from "@angular/core";

@Component({
  selector: "app-parent",
  template: `
    <div>
      <p>Count: {{ count() }}</p>
      <app-child
        (increment)="handleIncrement()"
        (decrement)="handleDecrement()"
      >
      </app-child>
    </div>
  `,
})
export class ParentComponent {
  count = signal(0);

  handleIncrement() {
    this.count.update((value) => value + 1);
  }

  handleDecrement() {
    this.count.update((value) => value - 1);
  }
}
