// src/data/examples/componentComposition/emitToParent/svelte4/Parent.svelte
<script>
  import ChildComponent from './ChildComponent.svelte'
  
  let count = 0
  
  function handleIncrement() {
    count++
  }
  
  function handleDecrement() {
    count--
  }
</script>

<div>
  <p>Count: {count}</p>
  <ChildComponent 
    on:increment={handleIncrement}
    on:decrement={handleDecrement}
  />
</div>

// src/data/examples/componentComposition/emitToParent/vue2/Parent.vue
<template>
  <div>
    <p>Count: {{ count }}</p>
    <ChildComponent @increment="handleIncrement" @decrement="handleDecrement" />
  </div>
</template>

<script>
import ChildComponent from "./ChildComponent.vue";

export default {
  components: { ChildComponent },
  data() {
    return {
      count: 0,
    };
  },
  methods: {
    handleIncrement() {
      this.count++;
    },
    handleDecrement() {
      this.count--;
    },
  },
};
</script>
