// src/data/examples/componentComposition/emitToParent/svelte5/Parent.svelte
<script>
  import ChildComponent from './ChildComponent.svelte'
  
  let count = $state(0)
  
  function handleIncrement() {
    count++
  }
  
  function handleDecrement() {
    count--
  }
</script>

<div>
  <p>Count: {count}</p>
  <ChildComponent 
    onincrement={handleIncrement}
    ondecrement={handleDecrement}
  />
</div>

// src/data/examples/componentComposition/emitToParent/react/Parent.jsx
import { useState } from 'react'
import ChildComponent from './ChildComponent'

function Parent() {
  const [count, setCount] = useState(0)
  
  const handleIncrement = () => {
    setCount(count + 1)
  }
  
  const handleDecrement = () => {
    setCount(count - 1)
  }
  
  return (
    <div>
      <p>Count: {count}</p>
      <ChildComponent 
        onIncrement={handleIncrement}
        onDecrement={handleDecrement}
      />
    </div>
  )
}

export default Parent
