// src/data/examples/componentComposition/slotFallback/vue3/CardComponent.vue
<template>
  <div class="card">
    <div class="card-body">
      <slot>
        <!-- Fallback content -->
        <h2>Default Title</h2>
        <p>No content provided</p>
      </slot>
    </div>
  </div>
</template>

<style scoped>
.card {
  border: 1px solid #ddd;
  border-radius: 8px;
  padding: 16px;
}
</style>

// src/data/examples/componentComposition/slot/angular-renaissance/card.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-card",
  template: `
    <div class="card">
      <div class="card-body">
        <ng-content></ng-content>
      </div>
    </div>
  `,
  styles: [
    `
      .card {
        border: 1px solid #ddd;
        border-radius: 8px;
        padding: 16px;
      }
    `,
  ],
  standalone: true,
})
export class CardComponent {}
