// src/data/examples/componentComposition/props/angular/parent.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-parent",
  template: `
    <div>
      <app-child [title]="pageTitle" [count]="counter" [isActive]="isActive">
      </app-child>
    </div>
  `,
})
export class ParentComponent {
  pageTitle = "Hello World";
  counter = 42;
  isActive = true;
}

// src/data/examples/componentComposition/props/vue3/Parent.vue
<template>
  <div>
    <ChildComponent :title="pageTitle" :count="counter" :is-active="isActive" />
  </div>
</template>

<script setup>
import { ref } from "vue";
import ChildComponent from "./ChildComponent.vue";

const pageTitle = ref("Hello World");
const counter = ref(42);
const isActive = ref(true);
</script>
