// src/data/examples/componentComposition/emitToParent/svelte4/ChildComponent.svelte
<script>
  import { createEventDispatcher } from 'svelte'
  
  const dispatch = createEventDispatcher()
  
  function increment() {
    dispatch('increment')
  }
  
  function decrement() {
    dispatch('decrement')
  }
</script>

<div>
  <button on:click={increment}>+</button>
  <button on:click={decrement}>-</button>
</div>

// src/data/examples/componentComposition/emitToParent/vue3/ChildComponent.vue
<template>
  <div>
    <button @click="increment">+</button>
    <button @click="decrement">-</button>
  </div>
</template>

<script setup>
const emit = defineEmits(['increment', 'decrement'])

const increment = () => {
  emit('increment')
}

const decrement = () => {
  emit('decrement')
}
</script>
