// src/data/examples/componentComposition/emitToParent/angular/child.component.ts
import { Component, EventEmitter, Output } from "@angular/core";

@Component({
  selector: "app-child",
  template: `
    <div>
      <button (click)="onIncrement()">+</button>
      <button (click)="onDecrement()">-</button>
    </div>
  `,
})
export class ChildComponent {
  @Output() increment = new EventEmitter<void>();
  @Output() decrement = new EventEmitter<void>();

  onIncrement() {
    this.increment.emit();
  }

  onDecrement() {
    this.decrement.emit();
  }
}

// src/data/examples/componentComposition/emitToParent/vue3/ChildComponent.vue
<template>
  <div>
    <button @click="increment">+</button>
    <button @click="decrement">-</button>
  </div>
</template>

<script setup>
const emit = defineEmits(['increment', 'decrement'])

const increment = () => {
  emit('increment')
}

const decrement = () => {
  emit('decrement')
}
</script>
