// src/data/examples/componentComposition/emitToParent/angular-renaissance/child.component.ts
import { Component, output } from "@angular/core";

@Component({
  selector: "app-child",
  template: `
    <div>
      <button (click)="onIncrement()">+</button>
      <button (click)="onDecrement()">-</button>
    </div>
  `,
})
export class ChildComponent {
  increment = output<void>();
  decrement = output<void>();

  onIncrement() {
    this.increment.emit();
  }

  onDecrement() {
    this.decrement.emit();
  }
}

// src/data/examples/componentComposition/emitToParent/vue3/ChildComponent.vue
<template>
  <div>
    <button @click="increment">+</button>
    <button @click="decrement">-</button>
  </div>
</template>

<script setup>
const emit = defineEmits(['increment', 'decrement'])

const increment = () => {
  emit('increment')
}

const decrement = () => {
  emit('decrement')
}
</script>
