// src/data/examples/componentComposition/emitToParent/svelte4/Parent.svelte
<script>
  import ChildComponent from './ChildComponent.svelte'
  
  let count = 0
  
  function handleIncrement() {
    count++
  }
  
  function handleDecrement() {
    count--
  }
</script>

<div>
  <p>Count: {count}</p>
  <ChildComponent 
    on:increment={handleIncrement}
    on:decrement={handleDecrement}
  />
</div>

// src/data/examples/componentComposition/emitToParent/vue3/Parent.vue
<template>
  <div>
    <p>Count: {{ count }}</p>
    <ChildComponent @increment="handleIncrement" @decrement="handleDecrement" />
  </div>
</template>

<script setup>
import { ref } from 'vue'
import ChildComponent from './ChildComponent.vue'

const count = ref(0)

const handleIncrement = () => {
  count.value++
}

const handleDecrement = () => {
  count.value--
}
</script>
