// src/data/examples/componentComposition/props/react/ChildComponent.tsx
interface ChildProps {
  title: string;
  count?: number;
  isActive?: boolean;
}

function ChildComponent({ title, count = 0, isActive = false }: ChildProps) {
  return (
    <div>
      <h1>{title}</h1>
      <p>Count: {count}</p>
      <p>Status: {isActive ? "Active" : "Inactive"}</p>
    </div>
  );
}

export default ChildComponent;

// src/data/examples/componentComposition/props/vue2/ChildComponent.vue
<template>
  <div>
    <h1>{{ title }}</h1>
    <p>Count: {{ count }}</p>
    <p>Status: {{ isActive ? "Active" : "Inactive" }}</p>
  </div>
</template>

<script>
export default {
  props: {
    title: {
      type: String,
      required: true,
    },
    count: {
      type: Number,
      default: 0,
    },
    isActive: {
      type: Boolean,
      default: false,
    },
  },
};
</script>
