// src/data/examples/componentComposition/props/angular/child.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "app-child",
  template: `
    <div>
      <h1>{{ title }}</h1>
      <p>Count: {{ count }}</p>
      <p>Status: {{ isActive ? "Active" : "Inactive" }}</p>
    </div>
  `,
})
export class ChildComponent {
  @Input() title!: string;
  @Input() count: number = 0;
  @Input() isActive: boolean = false;
}

// src/data/examples/componentComposition/props/react/ChildComponent.tsx
interface ChildProps {
  title: string;
  count?: number;
  isActive?: boolean;
}

function ChildComponent({ title, count = 0, isActive = false }: ChildProps) {
  return (
    <div>
      <h1>{title}</h1>
      <p>Count: {count}</p>
      <p>Status: {isActive ? "Active" : "Inactive"}</p>
    </div>
  );
}

export default ChildComponent;
