// src/data/examples/componentComposition/props/vue2/Parent.vue
<template>
  <div>
    <ChildComponent :title="pageTitle" :count="counter" :is-active="isActive" />
  </div>
</template>

<script>
import ChildComponent from "./ChildComponent.vue";

export default {
  components: { ChildComponent },
  data() {
    return {
      pageTitle: "Hello World",
      counter: 42,
      isActive: true,
    };
  },
};
</script>

// src/data/examples/componentComposition/props/angular/parent.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-parent",
  template: `
    <div>
      <app-child [title]="pageTitle" [count]="counter" [isActive]="isActive">
      </app-child>
    </div>
  `,
})
export class ParentComponent {
  pageTitle = "Hello World";
  counter = 42;
  isActive = true;
}
